window.POKE_PULLS_PRODUCTS = [
  {
    id: "common",
    name: "Common Scoop",
    type: "common",
    price: 8,
    cards: 30,
    rarityGuarantee: "30 common cards, one card per bead pulled.",
    condition: "Near mint to lightly played. No damaged cards packed.",
    shipping: "Ships in a team bag with basic card protection.",
    noGuarantee: "No specific card, character, set, artwork, or market value is guaranteed.",
    accent: "#3d9a52",
    bg: "#e4f6e9",
    icons: ["C", "?", "+"],
    tierLabel: "Common",
    baseCards: "30 common cards",
    bonus: "No bonus card or pack",
    description: "A starter mystery scoop for binder builders and younger collectors."
  },
  {
    id: "holo",
    name: "Common + Holo Scoop",
    type: "holo",
    price: 18,
    cards: 30,
    rarityGuarantee: "Includes common cards plus one sleeved holo or reverse-holo card.",
    condition: "Near mint to lightly played. No creased, torn, or water-damaged cards.",
    shipping: "Holo or reverse-holo card ships sleeved inside the team bag.",
    noGuarantee: "No specific holo, character, set, artwork, or market value is guaranteed.",
    accent: "#7665c9",
    bg: "#eeeafd",
    icons: ["H", "*", "?"],
    tierLabel: "Holo upgrade",
    baseCards: "30 common cards",
    bonus: "1 sleeved holo or reverse-holo card",
    description: "A common-card mystery scoop with a guaranteed sleeved shine."
  },
  {
    id: "ex",
    name: "Common + EX Scoop",
    type: "ex",
    price: 28,
    cards: 30,
    rarityGuarantee: "Includes common cards plus one sleeved EX-style hit card.",
    condition: "Near mint to lightly played. EX-style hits are inspected before packing.",
    shipping: "EX-style hit ships sleeved with protective team-bag packaging.",
    noGuarantee: "No specific EX card, character, set, artwork, or market value is guaranteed.",
    accent: "#d94b82",
    bg: "#ffe5ef",
    icons: ["EX", "*", "+"],
    tierLabel: "EX upgrade",
    baseCards: "30 common cards",
    bonus: "1 sleeved EX-style hit card",
    description: "A bigger reveal tier with common cards and one sleeved EX-style card."
  },
  {
    id: "pack",
    name: "Common + Pack Scoop",
    type: "pack",
    price: 45,
    cards: 50,
    rarityGuarantee: "Includes common cards plus one sealed booster-style pack or bonus pack add-on.",
    condition: "Near mint to lightly played. No damaged cards included.",
    shipping: "Ships with cards in team bags and the pack protected in the parcel.",
    noGuarantee: "No specific pack art, set, card, character, pull, or market value is guaranteed.",
    accent: "#e85043",
    bg: "#ffe8df",
    icons: ["P", "*", "+"],
    tierLabel: "Pack upgrade",
    baseCards: "50 common cards",
    bonus: "1 sealed booster-style pack or pack add-on",
    description: "The largest tier: common-card pull plus a pack-style bonus for gifting."
  },
  {
    id: "single-ex",
    name: "Single EX Card",
    type: "single",
    price: 5,
    cards: 1,
    countLabel: "1 sleeved EX-style card",
    rarityGuarantee: "Includes one sleeved EX-style card.",
    condition: "Near mint to lightly played. No creased, torn, or water-damaged cards.",
    shipping: "Ships sleeved with basic card protection.",
    noGuarantee: "No specific EX card, character, set, artwork, or market value is guaranteed.",
    accent: "#2777c6",
    bg: "#e5f1ff",
    icons: ["EX", "$5", "!"],
    tierLabel: "Single card",
    baseCards: "Bead scoop",
    bonus: "1 EX-style card",
    description: "A simple five-dollar option for collectors who just want an EX-style card."
  }
];
